name: Lint

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install-dependencies
        run: |
             sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
             sudo apt-get install libwayland-dev libxkbcommon-dev
      - uses: actions-rs/cargo@v1
        name: "check format"
        with:
          command: fmt
          args: --check
      - uses: actions-rs/cargo@v1
        name: "check lint with clippy"
        with:
          command: clippy
          args: -- -D warnings
